version: '3.4'

services:
  traviscommsidentitylocaldb:
   image: "mcr.microsoft.com/mssql/server:2019-latest"
   environment:
     - ACCEPT_EULA=Y
     - SA_PASSWORD=P@ssw0rd123
   ports:
    - 1433:1433
   expose:
    - 1433

  org.identityserver:
    image: ${DOCKER_REGISTRY-}orgidentityserver
    build:
      context: .
      dockerfile: Org.IdentityServer/Dockerfile
    depends_on:
      - traviscommsidentitylocaldb
    ports:
     - 5001:443

